import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PDFDocument} from 'pdf-lib';
import {createScanPdf,organizePdfs,pdfSettings,ocrTokens} from '../src/pdf-tools.js';
const image=new Uint8Array(fs.readFileSync(new URL('./fixture.png',import.meta.url)));
const render=async()=>({bytes:image,width:600,height:800});
const doc={name:'Test scan',pages:[{ocrText:'SCANNER TEST'},{ocrText:'Second page'}]};
const fonts=['NotoSans','NotoSansDevanagari'].map(n=>new Uint8Array(fs.readFileSync(new URL(`../assets/fonts/${n}.ttf`,import.meta.url))));
for(const size of ['A4','Letter','Legal'])for(const orientation of ['Portrait','Landscape'])for(const pageNumbers of [false,true])test(`PDF ${size}/${orientation}/numbers=${pageNumbers}`,async()=>{
 const blob=await createScanPdf(doc,render,{size,orientation,pageNumbers});const pdf=await PDFDocument.load(await blob.arrayBuffer());assert.equal(pdf.getPageCount(),2);const page=pdf.getPage(0);assert.equal(page.getWidth()>page.getHeight(),orientation==='Landscape');assert.equal(pdf.getTitle(),doc.name);
});
test('AES-256 PDF requires a password',async()=>{const blob=await createScanPdf(doc,render,{password:'sample-password'});assert.match(await blob.text(),/AESV3/);await assert.rejects(PDFDocument.load(await blob.arrayBuffer()),/encrypted/);});
test('searchable PDF embeds Unicode fonts',async()=>{const blob=await createScanPdf(doc,render,{searchable:true,fonts});const pdf=await PDFDocument.load(await blob.arrayBuffer());assert.equal(pdf.getPageCount(),2);assert.match(await blob.text(),/ToUnicode/);});
test('searchable + AES-256 combination',async()=>{const blob=await createScanPdf(doc,render,{searchable:true,fonts,password:'strong-test-password'});assert.match(await blob.text(),/AESV3/);});
test('empty OCR blocks searchable export',async()=>assert.rejects(createScanPdf({pages:[{}]},render,{searchable:true}),/Run OCR/));
test('empty document export rejected',async()=>assert.rejects(createScanPdf({pages:[]},render),/Add a page/));
test('invalid margin rejected',()=>assert.throws(()=>pdfSettings({margin:-1})));
test('invalid quality rejected',()=>assert.throws(()=>pdfSettings({quality:2})));
test('overlong password rejected without truncation',()=>assert.throws(()=>pdfSettings({password:'x'.repeat(128)})));
test('ID sheet puts front and back on one A4 page',async()=>{const blob=await createScanPdf(doc,render,{idSheet:true});const pdf=await PDFDocument.load(await blob.arrayBuffer());assert.equal(pdf.getPageCount(),1);assert.equal(pdf.getPage(0).getWidth(),595.28);});
test('ID sheet rejects more than two pages',async()=>assert.rejects(createScanPdf({pages:[{},{},{}]},render,{idSheet:true}),/one or two/));
test('PDF organizer merges, reorders, rotates, stamps and numbers',async()=>{const source=await PDFDocument.create();source.addPage([100,200]).drawText('First');source.addPage([300,400]).drawText('Second');const bytes=await source.save();const blob=await organizePdfs([{bytes,selection:'2,1'},{bytes,selection:'1'}],{rotation:90,stamp:'Reviewed',pageNumbers:true});const result=await PDFDocument.load(await blob.arrayBuffer());assert.equal(result.getPageCount(),3);assert.equal(result.getPage(0).getWidth(),300);assert.equal(result.getPage(0).getRotation().angle,90);});
test('encrypted input is not silently bypassed by organizer',async()=>{const blob=await createScanPdf(doc,render,{password:'sample-password'});await assert.rejects(organizePdfs([{bytes:await blob.arrayBuffer()}]),/encrypted/);});
test('malformed PDF fails',async()=>assert.rejects(organizePdfs([{bytes:new Uint8Array([1,2,3])}]),/Could not read PDF/));
test('empty organizer rejected',async()=>assert.rejects(organizePdfs([]),/at least one/));
test('OCR bounding boxes normalized to image size',()=>{const result=ocrTokens({text:'Word',blocks:[{paragraphs:[{lines:[{words:[{text:'Word',bbox:{x0:10,y0:20,x1:40,y1:60}}]}]}]}]},100,200);assert.deepEqual(result.ocrWords[0],{text:'Word',x:.1,y:.1,w:.3,h:.2});});
test('render failure rejects the PDF export',async()=>assert.rejects(createScanPdf(doc,async()=>{throw Error('Image failed');}),/Image failed/));
test('abort signal cancels PDF export before rendering',async()=>{const controller=new AbortController();controller.abort();await assert.rejects(createScanPdf(doc,render,{signal:controller.signal}),/cancelled/);});
test('organizer enforces the 200-page result bound',async()=>{const source=await PDFDocument.create();for(let i=0;i<101;i++)source.addPage();const bytes=await source.save();await assert.rejects(organizePdfs([{bytes},{bytes}]),/200 pages/);});
test('ID sheets reject searchable mode instead of silently dropping OCR',async()=>assert.rejects(createScanPdf(doc,render,{idSheet:true,searchable:true,fonts}),/searchable PDF switched off/));
