import test from 'node:test';
import assert from 'node:assert/strict';
import {createStore} from '../src/store.js';
const fixture=()=>({id:'doc',name:'Test',createdAt:'2026-01-01',updatedAt:'2026-01-01',pages:[{id:'a',name:'A',crop:{tl:[0,0],tr:[100,0],br:[100,100],bl:[0,100]}},{id:'b',name:'B'}]});
async function setup() {let saved=[fixture()],fail=false,n=0;const io={read:async()=>structuredClone(saved),put:async d=>{if(fail)throw Error('Quota exceeded');saved=[d,...saved.filter(x=>x.id!==d.id)];},remove:async id=>{saved=saved.filter(x=>x.id!==id);}};const store=createStore(io,()=>String(++n));await store.load();return {store,setFail:v=>fail=v,getSaved:()=>saved};}
test('rapid independent edits preserve every field',async()=>{const {store}=await setup();await Promise.all([store.updatePage('doc','a',{brightness:110}),store.updatePage('doc','a',{contrast:120}),store.updatePage('doc','a',{rotation:90})]);assert.deepEqual({...store.documents[0].pages[0],crop:undefined},{id:'a',name:'A',crop:undefined,brightness:110,contrast:120,rotation:90});});
test('batch OCR saves text for every page',async()=>{const {store}=await setup();await store.updatePage('doc','a',{ocrText:'first'});await store.updatePage('doc','b',{ocrText:'second'});assert.deepEqual(store.documents[0].pages.map(p=>p.ocrText),['first','second']);});
test('quota errors do not publish unsaved changes and queue recovers',async()=>{const {store,setFail}=await setup();setFail(true);await assert.rejects(store.updatePage('doc','a',{rotation:90}),/Quota/);assert.equal(store.documents[0].pages[0].rotation,undefined);setFail(false);await store.updatePage('doc','a',{rotation:180});assert.equal(store.documents[0].pages[0].rotation,180);});
test('reordering then editing changes the correct stable page ID',async()=>{const {store}=await setup();await store.reorderPages('doc',0,1);await store.updatePage('doc','a',{ocrText:'A'});assert.equal(store.documents[0].pages[1].ocrText,'A');});
test('duplicate pages have independent crop objects and IDs',async()=>{const {store}=await setup();await store.duplicatePage('doc','a');const pages=store.documents[0].pages;assert.notEqual(pages[0].id,pages[1].id);pages[1].crop.tl[0]=42;assert.equal(pages[0].crop.tl[0],0);});
test('last page cannot be deleted',async()=>{const {store}=await setup();await store.deletePage('doc','a');await assert.rejects(store.deletePage('doc','b'),/at least one/);assert.equal(store.documents[0].pages.length,1);});
test('invalid reorder fails without dropping pages',async()=>{const {store}=await setup();await assert.rejects(store.reorderPages('doc',-1,0));assert.equal(store.documents[0].pages.length,2);});
test('merge leaves original documents unchanged and generates new page IDs',async()=>{const {store}=await setup();const copy=await store.duplicateDocument('doc');const merged=await store.mergeDocuments(['doc',copy.id]);assert.equal(merged.pages.length,4);assert.equal(new Set(merged.pages.map(p=>p.id)).size,4);assert.equal(store.documents.length,3);});
test('insert always remaps document and page IDs',async()=>{const {store}=await setup();const restored=await store.insert(fixture());assert.notEqual(restored.id,'doc');assert.notEqual(restored.pages[0].id,'a');});
test('saving page changes invalidates review',async()=>{const {store}=await setup();await store.updateDocument('doc',{reviewedAt:'today'});await store.updatePage('doc','a',{rotation:90});assert.equal(store.documents[0].reviewedAt,undefined);});
test('flush waits for pending edits',async()=>{const {store,getSaved}=await setup();store.updatePage('doc','a',{rotation:90});await store.flush();assert.equal(getSaved()[0].pages[0].rotation,90);});
test('subscriber sees only successfully committed mutations',async()=>{const {store,setFail}=await setup();let calls=0;const unsub=store.subscribe(()=>calls++);await store.updateDocument('doc',{name:'New'});setFail(true);await assert.rejects(store.updateDocument('doc',{name:'Lost'}));unsub();assert.equal(calls,1);});
test('flush reports failed saves instead of claiming success',async()=>{const {store,setFail}=await setup();setFail(true);await assert.rejects(store.updateDocument('doc',{name:'Lost'}));await assert.rejects(store.flush(),/Quota/);});
test('reordering invalidates the reviewed status',async()=>{const {store}=await setup();await store.updateDocument('doc',{reviewedAt:'today'});await store.reorderPages('doc',0,1);assert.equal(store.documents[0].reviewedAt,undefined);});
