import {notePages,dragRegion} from './text-pages.js';
import {preparePrint} from './print.js';
import {organizePdfs} from './pdf-tools.js';
import {download,fullCrop,canvasBlob,imageFromBytes,regionPixels} from './document-tools.js';
export function createAdvancedTools({React:R,useScanner,renderPage,makePdf,safeName,readImage,decodeQR,expandImports,recognizeRegion,RenderedPage,pdfjs}){
 const h=R.createElement,button=(text,onClick,disabled=false)=>h('button',{type:'button',onClick,disabled},text);
 function PdfOrganizer(){
  const [files,setFiles]=R.useState([]),[ranges,setRanges]=R.useState(new Map()),[selection,setSelection]=R.useState(''),[rotation,setRotation]=R.useState('0'),[stamp,setStamp]=R.useState(''),[numbered,setNumbered]=R.useState(false),[busy,setBusy]=R.useState(false),[status,setStatus]=R.useState('');
  return h('details',{className:'pt-tools'},h('summary',null,'PDF organizer · preserve text and graphics'),h('p',null,'Merge PDFs in the listed order, extract/reorder pages, rotate, number or watermark without turning them into images. Forms, links, bookmarks and digital signatures may not survive page copying; review the exported file.'),
   h('label',null,'Choose PDFs',h('input',{type:'file',accept:'.pdf',multiple:true,disabled:busy,onChange:e=>{setFiles(Array.from(e.target.files));setRanges(new Map());setStatus('');}})),
   h('ol',null,files.map((f,i)=>h('li',{key:i},f.name+' ',h('label',null,'Pages for '+f.name,h('input',{value:ranges.get(f)||'',placeholder:'Use default range below',disabled:busy,onChange:e=>{const value=e.target.value;setRanges(previous=>new Map(previous).set(f,value));}})),button('Move up '+(i+1),()=>setFiles(items=>{const copy=[...items];[copy[i-1],copy[i]]=[copy[i],copy[i-1]];return copy;}),busy||i===0),button('Remove '+(i+1),()=>setFiles(items=>items.filter((_,n)=>n!==i)),busy)))),
   h('label',null,'Default pages from each PDF',h('input',{value:selection,onChange:e=>setSelection(e.target.value),placeholder:'All, or 3,1-2','aria-label':'PDF organizer page ranges',disabled:busy})),
   h('label',null,'Rotate each page',h('select',{value:rotation,onChange:e=>setRotation(e.target.value),disabled:busy},[0,90,180,270].map(v=>h('option',{value:v,key:v},v+'°')))),
   h('label',null,'Watermark text',h('input',{value:stamp,onChange:e=>setStamp(e.target.value),maxLength:100,disabled:busy})),
   h('label',null,h('input',{type:'checkbox',checked:numbered,onChange:e=>setNumbered(e.target.checked),disabled:busy}),'Add page numbers'),
   button('Export organized PDF',async()=>{setBusy(true);setStatus('Reading selected PDFs…');try{const inputs=[];for(const file of files){if(file.size>100*1024*1024)throw Error('Each PDF must be below 100 MB.');inputs.push({bytes:await file.arrayBuffer(),selection:ranges.get(file)?.trim()||selection});}const blob=await organizePdfs(inputs,{rotation,stamp,pageNumbers:numbered});download(blob,'organized.pdf');setStatus('Organized PDF downloaded. Original PDFs are unchanged.');}catch(e){setStatus(e.message);}finally{setBusy(false);}},busy||!files.length),h('p',{role:'status'},status));
 }
 function Convenience({doc,page,onSelect,onPreview}){
  const api=useScanner(),[status,setStatus]=R.useState(''),[busy,setBusy]=R.useState(false),[password,setPassword]=R.useState(''),[repeat,setRepeat]=R.useState(''),[region,setRegion]=R.useState({x:10,y:10,w:30,h:15}),[blank,setBlank]=R.useState(''),[regionText,setRegionText]=R.useState('');
  const run=async fn=>{setBusy(true);setStatus('');try{await api.flush();await fn();}catch(e){setStatus(e.message);}finally{setBusy(false);}};
  const dragStart=R.useRef(null);
  const options=doc.pdfOptions||{};
  const setOption=(key,value)=>run(()=>api.updatePdfOptions(doc.id,{[key]:value}));
  const previewOptions=()=>{if(password!==repeat)throw Error('The PDF passwords do not match.');if(password&&password.length<8)throw Error('Use at least 8 characters for the PDF password.');return {password};};
  const output=async()=>{const fresh=await api.getDocument(doc.id);return makePdf(fresh,previewOptions());};

  return h('div',{className:'pt-tools'},h('div',{className:'pt-actions'},
   button('Undo edit',()=>run(async()=>{await api.undo(doc.id);onSelect(0);setStatus('Undone. History is kept for this session.');}),busy),button('Redo edit',()=>run(async()=>{await api.redo(doc.id);onSelect(0);setStatus('Redone.');}),busy),
   button('Copy page text',()=>run(async()=>{if(!page.ocrText?.trim())throw Error('Run OCR first.');await navigator.clipboard.writeText(page.ocrText);setStatus('Page text copied.');}),busy)),
   h('details',null,h('summary',null,'PDF security, search & print layout'),
    h('label',null,h('input',{type:'checkbox',checked:!!options.searchable,onChange:e=>setOption('searchable',e.target.checked),disabled:busy}),'Searchable PDF (run OCR on every page first)'),
    h('label',null,h('input',{type:'checkbox',checked:!!options.pageNumbers,onChange:e=>setOption('pageNumbers',e.target.checked),disabled:busy}),'Page numbers'),
    h('label',null,h('input',{type:'checkbox',checked:!!options.idSheet,onChange:e=>setOption('idSheet',e.target.checked),disabled:busy}),'ID front/back on A4 (one or two pages, 85.6 × 54 mm boxes)'),
    h('label',null,'Paper size',h('select',{value:options.size||'A4',disabled:busy,onChange:e=>setOption('size',e.target.value)},['A4','Letter','Legal'].map(v=>h('option',{key:v,value:v},v)))),h('label',null,'Orientation',h('select',{value:options.orientation||'Portrait',disabled:busy,onChange:e=>setOption('orientation',e.target.value)},['Portrait','Landscape'].map(v=>h('option',{key:v,value:v},v)))),
    h('label',null,'PDF margin (points)',h('input',{type:'number',min:0,max:100,value:options.margin??18,onChange:e=>setOption('margin',Number(e.target.value)),disabled:busy})),
    h('label',null,'PDF password (optional)',h('input',{type:'password',autoComplete:'new-password',value:password,onChange:e=>setPassword(e.target.value)})),
    h('label',null,'Confirm PDF password',h('input',{type:'password',autoComplete:'new-password',value:repeat,onChange:e=>setRepeat(e.target.value)})),
    h('p',null,'Passwords are used only for exports from this panel and are not saved in browser storage. Exported passwords use AES-256. Regular Export remains unencrypted. Print ID sheets at actual size (100%).'),
    h('div',{className:'pt-actions'},button('Preview configured PDF',()=>run(async()=>onPreview(await api.getDocument(doc.id),previewOptions())),busy),button('Download configured PDF',()=>run(async()=>{download(await output(),safeName(doc.name,'scan')+'.pdf');setStatus('Configured PDF downloaded.');}),busy),
      button('Print document',()=>{const printWindow=window.open('','_blank');if(!printWindow){setStatus('Allow a new window to print.');return;}run(async()=>{try{if(password)throw Error('Clear the export password before printing.');const fresh=await api.getDocument(doc.id);await preparePrint(pdfjs,await makePdf(fresh,{password:''}),printWindow,doc.name);setStatus('Print window opened. Use Print / save as PDF there.');}catch(e){printWindow.close();throw e;}});},busy))),
   h('details',null,h('summary',null,'More page tools'),
    h('div',{className:'pt-actions'},button('Reverse page order',()=>run(()=>api.reversePages(doc.id)),busy),button('Rotate all pages',()=>run(()=>api.rotateAll(doc.id)),busy),
      button('Read QR from page',()=>run(async()=>{const result=await renderPage(page);const code=await decodeQR(new Blob([result.bytes],{type:'image/jpeg'}));setStatus(code?'QR content: '+code:'No QR code found.');}),busy),
      button('Transparent signature PNG',()=>run(async()=>{const result=await renderPage(page),image=await imageFromBytes(result.bytes),canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);image.close();const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<pixels.data.length;i+=4){const grey=(pixels.data[i]+pixels.data[i+1]+pixels.data[i+2])/3;pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=0;pixels.data[i+3]=255-grey;}ctx.putImageData(pixels,0,0);download(await canvasBlob(canvas),safeName(page.name,'signature')+'.png');setStatus('Transparent signature downloaded. Best with dark ink on white paper.');}),busy)),
    h('label',null,'New text page',h('textarea',{value:blank,onChange:e=>setBlank(e.target.value),placeholder:'Type or paste notes',maxLength:4000})),
    button('Append text pages',()=>run(async()=>{const pages=await notePages(blank,readImage);await api.append(doc.id,pages);setBlank('');setStatus(pages.length+' searchable text page(s) appended.');}),busy)),
   h('details',null,h('summary',null,'Region OCR & redaction'),h('p',null,'Creates a separate flattened redacted document with no OCR layer. The original document and existing backups remain unchanged; never share those if they contain sensitive text.'),
    h('p',null,'Drag across the page to select a region, or enter percentages below.'),h('div',{className:'pt-region-preview','aria-label':'Select region on page',onPointerDown:e=>{if(busy)return;e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect();dragStart.current=[(e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100];},onPointerMove:e=>{if(!dragStart.current)return;const r=e.currentTarget.getBoundingClientRect();setRegion(dragRegion(dragStart.current,[(e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100]));},onPointerUp:()=>{dragStart.current=null;},onPointerCancel:()=>{dragStart.current=null;}},h(RenderedPage,{page,alt:'Region selection preview'}),h('div',{className:'pt-region-box',style:{left:region.x+'%',top:region.y+'%',width:region.w+'%',height:region.h+'%'}})),
    ...Object.keys(region).map(key=>h('label',{key},({x:'Left',y:'Top',w:'Width',h:'Height'}[key])+' (%)',h('input',{type:'number',min:0,max:100,value:region[key],onChange:e=>setRegion({...region,[key]:Number(e.target.value)})}))),
    button('Read text in region',()=>run(async()=>{const result=await renderPage(page),rect=regionPixels(region,result.width,result.height),image=await imageFromBytes(result.bytes),canvas=document.createElement('canvas');canvas.width=rect.w;canvas.height=rect.h;canvas.getContext('2d').drawImage(image,rect.x,rect.y,rect.w,rect.h,0,0,rect.w,rect.h);image.close();const text=await recognizeRegion(await canvasBlob(canvas));setRegionText(text);setStatus(text?'Region text ready. Original page OCR is unchanged.':'No text recognized in this region.');}),busy),h('label',null,'Region text',h('textarea',{value:regionText,onChange:e=>setRegionText(e.target.value)})),button('Copy region text',()=>run(async()=>{await navigator.clipboard.writeText(regionText);setStatus('Region text copied.');}),busy||!regionText),
    button('Create redacted copy',()=>run(async()=>{regionPixels(region,100,100);const result=await renderPage(page),image=await imageFromBytes(result.bytes),canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);image.close();ctx.fillStyle='black';const rect=regionPixels(region,canvas.width,canvas.height);ctx.fillRect(rect.x,rect.y,rect.w,rect.h);const src=await readImage(new File([await canvasBlob(canvas)],'redacted.png',{type:'image/png'}));await api.insert({name:doc.name+' redacted',mode:'document',tags:[],pages:[{name:'Redacted page',src,crop:fullCrop(),rotation:0,filter:'original',brightness:100,contrast:100,ink:[]}]});setStatus('Redacted copy created in library. Review its exact covered region before sharing.');}),busy)),
   h('p',{role:'status','aria-live':'polite'},busy?'Working…':status));
 }
 function DropImport(){const api=useScanner(),[notice,setNotice]=R.useState(''),[busy,setBusy]=R.useState(false);const handle=async files=>{setBusy(true);try{const expanded=await expandImports(Array.from(files));const doc=await api.createDocument(expanded);location.href=(window.__APP_BASE__||'')+'/edit/'+doc.id;}catch(e){setNotice(e.message);}finally{setBusy(false);}};return h('div',{className:'pt-drop',onDragOver:e=>e.preventDefault(),onDrop:e=>{e.preventDefault();if(!busy)handle(e.dataTransfer.files);},onPaste:e=>{const images=Array.from(e.clipboardData.files);if(images.length&&!busy){e.preventDefault();handle(images);}},tabIndex:0,role:'region','aria-label':'Drop or paste documents'},busy?'Importing…':'Drop images/PDFs here, or focus here and paste an image.',notice&&h('p',{role:'status'},notice));}
 return {Convenience,PdfOrganizer,DropImport};
}
